### ISSUE TITLE
##[error]7 after "Generating report..."

### ISSUE THREAD

**Issue by dbackeus** [moneyforward/brakeman-action#1]
Example output:
<img width="1289" alt="Screenshot 2020-06-24 at 14 27 22" src="https://user-images.githubusercontent.com/3461/85556238-f134c000-b626-11ea-808a-64e9100b5df5.png">

Here's the workflow yml used:
```yml
name: brakeman
on: pull_request
jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: moneyforward/brakeman-action@v0
```

I'm too new to GitHub Actions to figure out how to debug this myself. Let me know if there is any more data I can provide.
